---
swagger: "2.0"
info:
  title: "Public Six Degrees API"
  description: "Public Six Degrees API"
  version: "2016-02-08T11:30:22Z"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /most-mentioned-people:
    get:
      parameters:
        - name: "Accept"
          in: "header"
          required: true
          type: "string"
        - in: "body"
          name: "Empty"
          required: true
          schema:
            $ref: "#/definitions/Empty"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers: {}

definitions:
  Empty:
    type: "object"
  Person:
    type: object
    properties:
      id:
        type: string
      apiUrl:
        type: string
      prefLabel:
        type: string
      types:
        $ref: "#/definitions/HomeAddress"
