---
swagger: "2.0"
info:
  title: "Public Six Degrees API"
  description: "Public Six Degrees API"
  version: "2016-02-08T11:30:22Z"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /connectedPeople/{uuid}:
    get:
      parameters:
        - in: "path"
          name: "uuid"
          description: "The UUID of the person we want to query."
          type: "string"
          required: true
        - in: "query"
          name: "fromDate"
          description: "Start date, in YYYYMMDD format. Defaults to one week ago."
          required: false
          type: string
        - in: "query"
          name: "toDate"
          description: "End date, in YYYYMMDD format. Defaults to today."
          required: false
          type: string
        - in: "query"
          name: "minimumConnections"
          description: "The minimum number of connections required for a connection to appear in the list. Defaults to 5."
          required: false
          type: integer
        - in: "query"
          name: "mock"
          description: "If true, will return mock data. Defaults to false."
          required: false
          type: boolean
        - in: "query"
          name: "limit"
          description: "Limits the number of connections returned. Defaults to 10."
          required: false
          type: integer
        - in: "query"
          name: "contentLimit"
          description: "Limits the number of content items returned per connection. Defaults to 20. Cannot be higher than 20."
          required: false
          type: boolean
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ConnectedPeople"
          headers: {}
  /mostMentionedPeople:
    get:
      parameters:
        - in: "query"
          name: "fromDate"
          description: "Start date, in YYYYMMDD format. Defaults to one week ago."
          required: true
          type: string
        - in: "query"
          name: "toDate"
          description: "End date, in YYYYMMDD format. Defaults to today."
          required: true
          type: string
        - in: "query"
          name: "limit"
          description: "The maximum number of mentioned people to return. Defaults to 20."
          required: false
          type: integer
        - in: "query"
          name: "mock"
          description: "If true, will return mock data. Defaults to false."
          required: false
          type: boolean
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/MostMentionedPeople"
          headers: {}

definitions:
  ConnectedPeople:
    type: array
    items:
      $ref: "#/definitions/ConnectedPerson"
  ConnectedPerson:
    type: object
    properties:
      person:
        $ref: "#/definitions/Person"
      count:
        type: integer
  MostMentionedPeople:
    type: array
    items:
      $ref: "#/definitions/Person"
  Person:
    type: object
    properties:
      id:
        type: string
      apiUrl:
        type: string
      prefLabel:
        type: string
      types:
        type: array
        items:
          type: string
