---
swagger: "2.0"
info:
  title: "Public Six Degrees API"
  description: "Public Six Degrees API"
  version: "2016-02-08T11:30:22Z"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /most-mentioned-people:
    get:
      parameters:
        - in: "body"
          name: "Empty"
          required: true
          schema:
            $ref: "#/definitions/Empty"
        - in: "query"
          name: "start_date"
          required: true
          type: string
        - in: "query"
          name: "end_date"
          required: true
          type: string
        - in: "query"
          name: "limit"
          required: true
          type: string
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/MostMentionedPeople"
          headers: {}

definitions:
  Empty:
    type: "object"
  MostMentionedPeople:
    type: object
    properties:
      people:
        type: array
        items: 
          $ref: "#/definitions/Person"
      count:
        type: integer
  Person:
    type: object
    properties:
      id:
        type: string
      apiUrl:
        type: string
      prefLabel:
        type: string
      types:
        type: array
        items: string
